repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.9.7
      hooks:
          # Run the linter.
          - id: ruff
            args: [--fix]
          # Run the formatter.
          - id: ruff-format
    - repo: local
      hooks:
          - id: pyright
            name: pyright type checking
            entry: uv run pyright
            language: system
            types: [python]
    - repo: local
      hooks:
          - id: pytest
            name: Run pytest
            entry: uv run pytest tests
            language: system
            types: [python]
